[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Sitemap yönlendirmeleri
[[redirects]]
  from = "/sitemap-jobs.xml"
  to = "/.netlify/functions/sitemap-jobs"
  status = 200

# SEO friendly redirects
[[redirects]]
  from = "/jobs/*"
  to = "/is-ilanlari/:splat"
  status = 301

[[redirects]]
  from = "/job/*"
  to = "/ilan/:splat"
  status = 301

[[redirects]]
  from = "/career/*"
  to = "/kariyer/:splat"
  status = 301

# PayTR Callback URL
[[redirects]]
  from = "/api/paytr-callback"
  to = "/.netlify/functions/paytr-callback"
  status = 200
  force = true

[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200

# Robots.txt
[[redirects]]
  from = "/robots.txt"
  to = "/robots.txt"
  status = 200

# Ana SPA yönlendirmesi (en sonda olmalı)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for XML files - CRITICAL for sitemap recognition
[[headers]]
  for = "/sitemap*.xml"
  [headers.values]
    Content-Type = "application/xml; charset=utf-8"
    Cache-Control = "public, max-age=3600"
    X-Robots-Tag = "index, follow"
    Link = "</sitemap.xml>; rel=sitemap; type=application/xml"
    Access-Control-Allow-Origin = "*"

# Headers for better SEO and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-XSS-Protection = "1; mode=block"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    X-Robots-Tag = "index, follow, max-snippet:-1, max-image-preview:large"
    X-UA-Compatible = "IE=edge"
    X-DNS-Prefetch-Control = "on"
    Link = "</sitemap.xml>; rel=sitemap; type=application/xml"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache images
[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000"